### ISSUE TITLE
Better visualization [Open for discussion]

### ISSUE THREAD

**Issue by m172205** [jendralhxr/uget2#4]
Currently the visualizations are done using matlab. I would like to use pure python for visualization. 

Bijimane kumendan @jendralhxr ?

**Comment by jendralhxr** [comment]
pakai matplotlib kali nyak.
go ahead, after all they are just normal plots

ni pakai akun github alternatif ceritanya tidak mau memberantakkan portofolio akun utamanya, nyak?

**Comment by jendralhxr** [comment]
![image](https://user-images.githubusercontent.com/2327715/221485719-123e2dcc-f62a-4e71-9b0a-16cbedc9b24d.png)
selective blob tracking

**Comment by m172205** [comment]
nicee
