### ISSUE TITLE
ndak bisa nyimpen video

### ISSUE THREAD

**Issue by jendralhxr** [jendralhxr/uget2#8]
yang bikin penyakit ndak bisa simpen video dengan bener datangnya dari routine bikin masking.
https://github.com/jendralhxr/uget2/commit/9e6486e12c42ffca14a74b135cb5b9cf4b31b5b1

aku coba matikan mousecallback, tetep macet
aku coba tutup window, tetep macet (keknya emang ndak ngaruh)
apanya sih, ya?

semoga kalau masking pakai drawing dari tkinter, masalah ini lekas selesai

**Comment by jendralhxr** [comment]
alternatifnya (yang terbukti resmi bisa) pakai https://github.com/chenxinfeng4/ffmpegcv
tapi ffmpegcv mensyarakatkan pasang ffmpeg sendiri dan ukuran file yang dihasilkan lebih besar (aku bingung ngatur codec-e yakopo)

**Comment by jendralhxr** [comment]
ffmpegcv ukuran file-nya ternyata masuk akal waktu running di linux pakai codec h264

**Comment by jendralhxr** [comment]
ffmpegcv ukuran file-nya ternyata masuk akal waktu running di linux pakai codec h264

**Comment by satrialoka** [comment]
noice
