### ISSUE TITLE
MVC tkinter

### ISSUE THREAD

**Issue by m172205** [jendralhxr/uget2#9]
Meskipun saya bukan software enjinier, saya mencoba untuk berpikir seperti mereka
tkinter app kita akan pakai MVC _pattern_, _pattern_ yang cukup jadul tapi _it works_:

https://stackoverflow.com/questions/62573596/how-to-implement-a-tkinter-app-with-an-mvc-architecture

semoga hasilnya enak dibaca dan _transferable_ ke _project2_ selanjutnya.
meskipun saya hanya ahli masakan perancis asli padang

**Comment by m172205** [comment]
use https://pypi.org/project/attrdict/
instead of standard dict?

**Comment by jendralhxr** [comment]
> use https://pypi.org/project/attrdict/ instead of standard dict?

native dict aja oke

**Comment by jendralhxr** [comment]
sudah semacam essip jalan
